import type { Video, Playlist } from '@/lib/types';

export const videos: Video[] = [
  {
    id: '1',
    title: 'Introduction to React Hooks',
    description: 'A deep dive into useState, useEffect, and other fundamental React Hooks. Perfect for beginners and those looking for a refresher.',
    thumbnailUrl: 'https://picsum.photos/seed/1/640/360',
    youtubeId: '6JyMBB4_aYc',
    channel: 'CodeAcademy',
    channelAvatarUrl: 'https://picsum.photos/seed/ca/48/48',
    views: '1.2M',
    uploadedAt: '2 months ago',
  },
  {
    id: '2',
    title: 'Advanced CSS Grid Techniques',
    description: 'Master CSS Grid with these advanced tips and tricks. We will cover responsive layouts, complex alignments, and more.',
    thumbnailUrl: 'https://picsum.photos/seed/11/640/360',
    videoUrl: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    channel: 'CodeAcademy',
    channelAvatarUrl: 'https://picsum.photos/seed/ca/48/48',
    views: '890K',
    uploadedAt: '5 months ago',
  },
  {
    id: '3',
    title: 'The Renaissance: Art and Culture',
    description: 'Explore the vibrant art and culture of the Renaissance period, from Leonardo da Vinci to Michelangelo.',
    thumbnailUrl: 'https://picsum.photos/seed/2/640/360',
    youtubeId: 'I6d2Z032o-c',
    channel: 'ArtExplorers',
    channelAvatarUrl: 'https://picsum.photos/seed/ae/48/48',
    views: '2.5M',
    uploadedAt: '1 year ago',
  },
  {
    id: '4',
    title: 'The Roman Empire: Rise and Fall',
    description: 'A comprehensive overview of the Roman Empire, from its legendary founding to its eventual collapse.',
    thumbnailUrl: 'https://picsum.photos/seed/3/640/360',
    youtubeId: 'OpO54S_3d_o',
    channel: 'HistoryUncovered',
    channelAvatarUrl: 'https://picsum.photos/seed/hu/48/48',
    views: '3.1M',
    uploadedAt: '11 months ago',
  },
  {
    id: '5',
    title: 'The Basics of Photosynthesis',
    description: 'Learn how plants convert sunlight into energy. A fundamental concept in biology explained simply.',
    thumbnailUrl: 'https://picsum.photos/seed/4/640/360',
    videoUrl: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4',
    channel: 'Science Simplified',
    channelAvatarUrl: 'https://picsum.photos/seed/ss/48/48',
    views: '980K',
    uploadedAt: '7 months ago',
  },
  {
    id: '6',
    title: 'Music Theory 101: Understanding Scales',
    description: 'A beginner\'s guide to musical scales, including major, minor, and pentatonic scales.',
    thumbnailUrl: 'https://picsum.photos/seed/5/640/360',
    youtubeId: 'rgaTLrZGlk0',
    channel: 'MelodyMasters',
    channelAvatarUrl: 'https://picsum.photos/seed/mm/48/48',
    views: '1.8M',
    uploadedAt: '9 months ago',
  },
];

export const playlists: Playlist[] = [
  {
    id: 'cs-101',
    name: 'Computer Science 101',
    description: 'Fundamental concepts of computer science, from algorithms to data structures.',
    thumbnailUrl: 'https://picsum.photos/seed/cs-playlist/320/180',
    videoIds: ['1', '2'],
  },
  {
    id: 'history-of-art',
    name: 'History of Art',
    description: 'A journey through the most significant art movements in history.',
    thumbnailUrl: 'https://picsum.photos/seed/art-playlist/320/180',
    videoIds: ['3'],
  },
  {
    id: 'ancient-civilizations',
    name: 'Ancient Civilizations',
    description: 'Explore the rise and fall of great empires of the ancient world.',
    thumbnailUrl: 'https://picsum.photos/seed/history-playlist/320/180',
    videoIds: ['4'],
  },
];
